const getRandomDateInLastThreeMonths = () => {
  const now = new Date();
  const threeMonthsAgo = new Date();
  threeMonthsAgo.setMonth(now.getMonth() - 3);

  const randomTime =
    Math.random() * (now.getTime() - threeMonthsAgo.getTime()) +
    threeMonthsAgo.getTime();
  return new Date(randomTime);
};

const posts = [
  {
    id: 1,
    userId: 1,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобри филмови на сите времиња",
    body: `Еве листа на некои од најдобрите филмови на сите времиња: "Кум", "Осмото чудо", "Паразит".`,
    likes: 15,
    dislikes: 3,
  },
  {
    id: 2,
    userId: 2,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Рецензија на филмот 'Титаник'",
    body: `Филмот 'Титаник' е епска љубовна приказна која завршува трагично. Одлична глума и неверојатна продукција.`,
    likes: 20,
    dislikes: 5,
  },
  {
    id: 3,
    userId: 3,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобри комедии за оваа година",
    body: `Ако сте во потрага по добри комедии, ви ги препорачувам "Книговез", "Речиси Славни", и "Големата Болница".`,
    likes: 10,
    dislikes: 2,
  },
  {
    id: 4,
    userId: 4,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Зошто го сакам 'Кум'?",
    body: `'Кум' е мојот омилен филм поради извонредната приказна, фантастичната глума и неверојатната атмосфера.`,
    likes: 18,
    dislikes: 4,
  },
  {
    id: 5,
    userId: 5,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови што треба да ги гледате оваа година",
    body: `На листата за оваа година ги имаме: "Вечните", "Спајдермен: Нема пат до дома", и "Дина".`,
    likes: 25,
    dislikes: 7,
  },
  {
    id: 6,
    userId: 1,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите анимации за деца",
    body: `Децата ги обожаваат анимациите како "Замрзнато кралство", "Историја на играчките", и "Миньоните".`,
    likes: 12,
    dislikes: 3,
  },
  {
    id: 7,
    userId: 2,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови за љубов и романса",
    body: `Ако сте во романтично расположение, погледнете ги "Нотинг Хил", "П.С. Те сакам", и "Гордост и предрасуда".`,
    likes: 30,
    dislikes: 1,
  },
  {
    id: 8,
    userId: 3,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Трилери што ќе ве држат на работ од седиштето",
    body: `Филмови како "Седум", "Исчезната", и "Тивко место" ќе ве држат напнати до самиот крај.`,
    likes: 22,
    dislikes: 4,
  },
  {
    id: 9,
    userId: 4,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите филмови на Марвел",
    body: `Марвел има неколку одлични филмови, вклучувајќи ги "Одмаздници: Крајот на играта", "Црниот Пантер", и "Железниот Човек".`,
    likes: 27,
    dislikes: 6,
  },
  {
    id: 10,
    userId: 5,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите научно-фантастични филмови",
    body: `За љубителите на научната фантастика, ви ги препорачувам "Интерстелар", "Матрикс", и "Блејд Ранер".`,
    likes: 19,
    dislikes: 2,
  },
  {
    id: 11,
    userId: 1,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови базирани на вистински настани",
    body: `Вистинските приказни понекогаш се поинтересни од фикцијата. Гледајте ги "Шиндлерова Листа", "Скотот од Лос Анџелес", и "Целта".`,
    likes: 13,
    dislikes: 3,
  },
  {
    id: 12,
    userId: 2,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобри филмови на Кристофер Нолан",
    body: `Кристофер Нолан е познат по своите комплексни и интелигентни филмови. Некои од најдобрите се "Интерстелар", "Мементо", и "Темниот Витез".`,
    likes: 22,
    dislikes: 5,
  },
  {
    id: 13,
    userId: 3,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Зошто 'Матрикс' е револуционерен филм?",
    body: `'Матрикс' го револуционизираше жанрот на научната фантастика со својата иновативна приказна и специјалните ефекти.`,
    likes: 17,
    dislikes: 4,
  },
  {
    id: 14,
    userId: 4,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите драмски филмови",
    body: `Драмите често ги истражуваат човечките емоции и конфликти. Препорачувам да ги гледате "Зелена Мила", "Големата Кратка", и "Бојаните".`,
    likes: 16,
    dislikes: 3,
  },
  {
    id: 15,
    userId: 5,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови со извонредни визуелни ефекти",
    body: `Филмови како "Аватар", "Гравитација", и "Деветтото небо" имаат неверојатни визуелни ефекти што ве оставаат без здив.`,
    likes: 21,
    dislikes: 6,
  },
  {
    id: 16,
    userId: 1,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите филмови за семејства",
    body: `Ако барате нешто што целото семејство може да го гледа, пробајте ги "Хари Потер", "Пинокио", и "Бамби".`,
    likes: 12,
    dislikes: 2,
  },
  {
    id: 17,
    userId: 2,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите акциони филмови",
    body: `Акциони филмови како "Брзи и бесни", "Џон Вик", и "Неуморливи" се полни со адреналин и возбудливи сцени.`,
    likes: 23,
    dislikes: 4,
  },
  {
    id: 18,
    userId: 3,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите хорор филмови",
    body: `Хорор филмови кои ќе ви предизвикаат трепет: "Исчезнато", "Тихо место", и "Омен".`,
    likes: 20,
    dislikes: 3,
  },
  {
    id: 19,
    userId: 4,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови кои ја освоија наградата Оскар",
    body: `Некои од најдобрите филмови се оние кои ја освоија наградата Оскар, како "Паризит", "Ла Ла Ленд", и "Кралот".`,
    likes: 28,
    dislikes: 7,
  },
  {
    id: 20,
    userId: 5,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите романтични комедии",
    body: `Романтични комедии како "10 работи што ги мразам кај тебе", "Кога Хари ја сретна Сали", и "Невестата-бегалка" се одлични за релаксација.`,
    likes: 17,
    dislikes: 3,
  },
  {
    id: 21,
    userId: 1,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови со одлична музика",
    body: `Музиката може да го направи филмот незаборавен. Примерите вклучуваат "Гладијатор", "Интерстелар", и "Црниот Пантер".`,
    likes: 19,
    dislikes: 2,
  },
  {
    id: 22,
    userId: 2,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите документарни филмови",
    body: `Документарните филмови може да бидат многу едукативни. Некои од најдобрите се "Дебелата вистина", "Наша планета", и "Џиро Соните за суши".`,
    likes: 22,
    dislikes: 4,
  },
  {
    id: 23,
    userId: 3,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Зошто 'Интерстелар' е ремек дело?",
    body: `'Интерстелар' е ремек дело поради неговата сложена приказна, фантастичните визуелни ефекти и епската музика.`,
    likes: 21,
    dislikes: 3,
  },
  {
    id: 24,
    userId: 4,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите филмови на Pixar",
    body: `Pixar има создадено неколку неверојатни анимации, вклучувајќи ги "Играчки приказна", "Наопаку", и "Кокос".`,
    likes: 18,
    dislikes: 4,
  },
  {
    id: 25,
    userId: 5,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови со најдобри сценарија",
    body: `Одличните сценарија се клучни за добар филм. Некои од најдобрите се "Палп фикција", "Социјалната мрежа", и "Човекот од сенка".`,
    likes: 23,
    dislikes: 5,
  },
  {
    id: 26,
    userId: 1,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови за супер херои",
    body: `Ако сакате супер херои, гледајте ги "Одмаздници", "Бетмен: Почеток", и "Железниот човек".`,
    likes: 20,
    dislikes: 3,
  },
  {
    id: 27,
    userId: 2,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите филмови со Роберт де Ниро",
    body: `Роберт де Ниро има извонредна кариера. Некои од неговите најдобри филмови се "Кум II", "Бесен бик", и "Добри момци".`,
    likes: 21,
    dislikes: 2,
  },
  {
    id: 28,
    userId: 3,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите филмови со Мерил Стрип",
    body: `Мерил Стрип е една од најдобрите актерки на сите времиња. Некои од нејзините најдобри филмови се "Ѓаволот носи Прада", "Софиев избор", и "Железната дама".`,
    likes: 22,
    dislikes: 4,
  },
  {
    id: 29,
    userId: 4,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Најдобрите филмови со Том Хенкс",
    body: `Том Хенкс е познат по своите извонредни улоги. Некои од најдобрите се "Форест Гамп", "Изгубени", и "Патот до Пропаст".`,
    likes: 23,
    dislikes: 3,
  },
  {
    id: 30,
    userId: 5,
    createdAt: getRandomDateInLastThreeMonths(),
    title: "Филмови кои ќе ви го стоплат срцето",
    body: `Некои филмови едноставно ве прават среќни. Препорачувам да ги гледате "Вака за љубовта", "Најдоброто од мене", и "Светлината помеѓу океаните".`,
    likes: 20,
    dislikes: 4,
  },
];
