import { StaticImageData } from "next/image";
import { TMovie } from "./types/types";

export const landingBannerMovies = [
  {
    imageSrc: "/assets/images/samoglas-plakat.png",
    title: "name1",
  },
  {
    imageSrc: "/assets/images/Zona_zamfirova.png",
    title: "name2",
  },
  {
    imageSrc: "/assets/images/Juzni_vetar.png",
    title: "name3",
  },
  {
    imageSrc: "/assets/images/treto-poluvreme.png",
    title: "name4",
  },
  {
    imageSrc: "/assets/images/sestri.png",
    title: "name5",
  },
  {
    imageSrc: "/assets/images/Balkankan.png",
    title: "name6",
  },
  {
    imageSrc: "/assets/images/dajte_muzika.png",
    title: "name7",
  },
];

export const bannersGroupMovies = [
  {
    imageSrc: "/assets/images/landing-banner.png",
    title: "name1",
  },
  {
    imageSrc: "/assets/images/vtorbanner.png",
    title: "name2",
  },
  {
    imageSrc: "/assets/images/tretbanner.png",
    title: "name3",
  },
];

export const movieGroup = [
  {
    imageSrc: "/assets/images/Mirage.png",
    title: "Mirage",
  },
  {
    imageSrc: "/assets/images/Rectangle 5.png",
    title: "Treto Poluvreme",
  },
  {
    imageSrc: "/assets/images/Zona_zamfirova.png",
    title: "Zona Zamfirova",
  },
  {
    imageSrc: "/assets/images/Balkankan.png",
    title: "Balkankan",
  },
  {
    imageSrc: "/assets/images/Juzni_vetar.png",
    title: "Juzni Vetar",
  },
];

export const kidsGroup = [
  {
    imageSrc: "/assets/images/Petko.png",
    title: "name1",
  },
  {
    imageSrc: "/assets/images/SamurajJack.png",
    title: "name2",
  },
  {
    imageSrc: "/assets/images/nashe_malo.png",
    title: "name3",
  },
  {
    imageSrc: "/assets/images/PowerPufGurls.png",
    title: "name4",
  },
  {
    imageSrc: "/assets/images/Fifi_and_the_Flowertots.png",
    title: "name5",
  },
];

export const docsGroup = [
  {
    imageSrc: "/assets/images/zrtva-poster.png",
    title: "name1",
  },
  {
    imageSrc: "/assets/images/Jaz-Sem-Frenk.png",
    title: "name2",
  },
  {
    imageSrc: "/assets/images/the-man-in-the-movie-camera.png",
    title: "name3",
  },
  {
    imageSrc: "/assets/images/tetoviranje-poster.png",
    title: "name4",
  },
  {
    imageSrc: "/assets/images/makedonska-saga-poster.png",
    title: "name5",
  },
];

export const seriesGroup = [];

export const podcastsGroup = [
  {
    imageSrc: "/assets/images/channels4_profile.png",
    title: "name1",
  },
  {
    imageSrc: "/assets/images/Irl.png",
    title: "name2",
  },
  {
    imageSrc: "/assets/images/sara-podcast_.png",
    title: "name3",
  },
  {
    imageSrc: "/assets/images/kuka_na_srekata.png",
    title: "name4",
  },
  {
    imageSrc: "/assets/images/samoglas-plakat.png",
    title: "name5",
  },
];

export const artists = [
  {
    name: "Toni Mihajlovski",
    bio: "Toni Mihajlovski is a Macedonian theater, motion picture and television actor, stand up comedian, presenter and showman. Mihajlovski was born in Kumanovo, Yugoslavia on the 1st of July, 1967. After completing The Faculty of Arts in Skopje at the Ss. Cyril and Methodius University in Skopje he became a member of the drama section in the Macedonian National Theater in 1994. During the 5th annual 'JoakimInterFest' in 2010 which took place in Kragujevac, Serbia, he received the award for best actor.",
    imageSrc: "/assets/artists/Toni Mihajlovski.png",
    movies: [
      "Avatar",
      "The Wolf of Wall Street",
      "Gotham",
      "Doctor Strange",
      "Toy Story",
      "Ice Age: The Meltdown",
      "Balcancan",
    ],
    awards: [
      "Venice Film Festival",
      "Asociación de Cronistas Cinematográficos de la Argentina",
      "Western Union Short Film Competition",
    ],
  },
  {
    name: "Sasko Kocev",
    bio: "Sasko Kocev is Macedonian actor and stand-up comedian. He finished his faculty in Skopje and graduated in the Faculty for Dramatic Arts in Skopje. He is very talented and he's probably one of the best Macedonian actors. He is well known for his hosting in lots of TV shows, festivals and happenings.",
    imageSrc: "/assets/artists/Sasko Kocev 1.png",
    movies: [
      "I Am Legend",
      "Interstellar",
      "Power",
      "Rogue One: A Star Wars Story",
      "WALL·E",
    ],
    awards: [
      "Australian Film Critics Association (AFCA)",
      "Grande Prêmio do Cinema Brasileiro",
      "French Syndicate of Cinema Critics",
    ],
  },
  {
    name: "Igor Dzambazov",
    imageSrc: "/assets/artists/Igor Dzambazov.png",
    bio: "Igor Dzambazov is a Macedonian actor, showman, TV presenter, comedian, singer, songwriter, and prosaist. He was born on July 15, 1963, in Skopje to composer Aleksandar Dzambazov and actress Ance Dzambazova. His grandfather was the renowned Macedonian actor Petre Prlicko.",
    movies: ["300", "Game of Thrones", "Narcos", "Assassin's Creed"],
    awards: [
      "International Indian Film Academy Awards",
      "Karnataka State Film Award",
      "The Lebanese Cinema Movie Guide Awards",
    ],
  },
  {
    name: "Rade Sherbedzija",
    imageSrc: "/assets/artists/Rade Sherbedzia.png",
    bio: "Rade Serbedzija was born in Bunic (Korenica) in 1946. Graduated from the Academy of Dramatic Arts in Zagreb. Still a student, he started to play the leading roles in films and theater productions. He is remembered as an outstanding Peer Gynt, Don Juan, Georgij, Melkior, Oedipus, Hamlet, Leon and Richard III. He wrote and published four books of poetry and released four albums, as well as directed 12 plays (Balade Petrice Kerempuha, Kazu da je sova nekad bila pekareva kci, Judita, Hrvatski slavuj...). ",
    movies: ["The Avengers", "Interstellar", "Vikings", "Sisterhood"],
    awards: [
      "London Film Critics Circle",
      "Fotogramas de Plata",
      "American Film Institute (AFI)",
    ],
  },
];

export const headerMovies = [
  {
    movieId: 1,
    imageSrc: "/assets/topBanner/Lazar.png",
    title: "Lazar",
    thumbnail: "/assets/images/Lazar.png",
    storyline:
      "Smuggling illegals into Europe, Lazar will be facing an impossible choice.",
    description:
      "The film is picturing one Macedonian story for the marginalized group of people. In the center is Lazar, young boy, who is struggling between his personal problems, family and moral dilemmas about the job that he works. The film is building its plot slowly, unpretentiously and realistic. The acting and directing are good and at the end the movie will make you think a little about the society where we live. The plot takes place in Macedonia, but it could be also a story about a marginalized group of people anywhere in the world. This is third feature of the director Svetozar Ristevski, after the first one, also Macedonian production `Mirage`, and the second, which is Canadian production, `Dear Mr. Gacy`. Worth watching. Good seven from me",
    releaseDate: "2015",
    awards: "1 win & 1 nomination",
    credits: {
      director: "Svetozar Ristevski",
      writer: "Svetozar Ristevski",
      actors: [
        "Vedran Zivolic",
        "Dejan Lilic",
        "Natasha Petrovic, Toni Mihajlovski",
      ],
    },
  },
  {
    movieId: 2,
    title: "Bal-Can-Can",
    imageSrc: "/assets/topBanner/Balkankan.png",
    thumbnail: "/assets/images/Balkankan.png",
    storyline:
      "A Macedonian military deserter and his Italian blood-brother are searching for a dead grandmother.",
    description:
      "Bal-Can-Can is a 2005 Macedonian-Italian joint production film about a deserter who travels throughout the Balkans as a political immigrant in search of his dead mother-in-law who is wrapped in a carpet.",
  },
  {
    movieId: 3,
    title: "Treto Poluvreme",
    imageSrc: "/assets/topBanner/TretoPoluvreme.png",
    thumbnail: "/assets/images/treto-poluvreme.png",
    storyline:
      "Dimitry hires German coach Rudolph Spitz to galvanize his ragtag team into the country's best football club, but then the first Nazi tanks roll in and Rebecca, a local banker's beautiful daughter, elopes with his star player.",
    description:
      "THE THIRD HALF is a deeply moving, life-affirming and often humorous story of love during war-time and a country's passion for soccer. In 1941 Macedonia, a young Eastern Orthodox, Kosta, and a wealthy young Jewish woman, Rebecca, fall in love, despite her father's effort to keep them apart. With the war raging around their borders, the Macedonians remain cocooned in their world of patriotic pleasures, primarily concerned about getting the beleaguered Macedonia Football Club on a winning streak. Their manager hires the legendary German-Jewish coach Rudolph Spitz to turn them into champions. But when the Nazi occupation begins and they start deporting Jews, Kosta and his teammates realize that the carefree days of their youth are over. As the Nazis try to sabotage the outcome of the championship game, and Spitz's life is threatened, Kosta and his teammates rise to the challenge to protect their coach, with all of Macedonia cheering them on.",
  },
  {
    movieId: 4,
    title: "To the Hilt",
    imageSrc: "/assets/topBanner/Dobalcak.png",
    thumbnail: "/assets/images/Do-balcak.png",
    storyline:
      "An open-minded European woman flirts with three men and puts them through a series of tasks and events which turn out to have serious consequences.",
    description:
      "Macedonia is a small country, in the heart of the Balkans, which for five centuries was under the yoke of the Ottoman Empire. The action of the film To the Hilt takes place in the years of the general collapse and free fall, after the Macedonian uprising of 1903 which was extinguished in blood. The story is a love quadrangle between an uncompromising idealist rebel, a merciless Turkish officer, an opportunist rich man's son returning home after his studies in Europe and a lucid and open minded European woman, who flirts with the three men and puts in train a series of events with dire consequences, that she could hardly imagine. The characters go through turbulent collisions which lead them to cathartic experiences and new self-awareness. The film is a harsh and romantic story in which the eternal Macedonian cause for own identity and independence is seen through the prism of relativity of the ideas of freedom, justice, love, sacrifice, and treason. The story dramatizes and parodies the myth and anti-myth of East and West, of Europe and the Balkans. It leads to a boiling point the paradoxes and absurdities of Macedonian history.",
  },
];

export const comments = [
  {
    id: "124",
    userId: "11111",
    time: 10,
    text: "Kakov film nenormalno dobar e, ne znam sto ne go gledav pred",
    image: "/assets/users/user1.png",
    name: "Marija",
  },

  {
    id: "12435",
    userId: "111131",
    time: 20,
    text: "hmmm interesting movie",
    image: "/assets/users/user2.png",
    name: "Jana",
  },
  {
    id: "123",
    userId: "111131",
    time: 20,
    text: "WOWWW Kakva scena",
    image: "/assets/users/user3.png",
    name: "Jovan",
  },
];

const newMovies: TMovie[] = [
  {
    id: 1,
    title: "Balkankan",
    type: "Movie",
    genres: ["Comedy", "Drama"],
    posterImage: "/assets/images/Balkankan.png",
    duration: 120,
    releaseDate: "2005-05-15",
    storyline:
      "A comedy that explores the lives of people in the Balkans during the turbulent 1990s.",
    description:
      "Balkankan is a comedic drama that captures the essence of life in the Balkans with humor and poignancy.",
    actors: ["Borce Nacev", "Nikola Kojo"],
    directors: ["Darko Mitrevski", "Toni Mihajlovski"],
    awards: ["Best Balkan Film Award"],
    videoSrc: "http://example.com/balkankan_trailer.mp4",
    writers: ["Darko Mitrevski"],
    producers: ["Vardar Film"],
    cinematography: ["Vlatko Samoilovski"],
    costumeDesign: ["Aleksandra Andreevska"],
    editing: ["Dragan Milic"],
    views: 250,
  },
  {
    id: 2,
    title: "Balkanska Meka",
    type: "Documentary",
    genres: ["History"],
    posterImage: "/assets/images/balkanska_meka.png",
    duration: 90,
    releaseDate: "2010-04-20",
    storyline:
      "An in-depth documentary about the cultural heritage and history of the Balkan region.",
    description:
      "balkanska meka provides a detailed look into the rich history and traditions of the Balkan Peninsula.",
    actors: [],
    directors: ["Mile Stojanov"],
    awards: ["Historical Documentary Award"],
    videoSrc: "http://example.com/balkanska_meka_trailer.mp4",
    writers: ["Mile Stojanov"],
    producers: ["MRT"],
    cinematography: ["Petar Samardziev"],
    costumeDesign: ["Ana Stefanovska"],
    editing: ["Violeta Kalajdzieva"],
    views: 2350,
  },
  {
    id: 3,
    title: "Brza Pomosh",
    type: "Series",
    genres: ["Drama", "Medical"],
    posterImage: "/assets/images/brza-pomosh.png",
    duration: 45345,
    releaseDate: "2015-09-10",
    storyline:
      "Follows the lives of paramedics and doctors working in an emergency medical service in Macedonia.",
    description:
      "A medical drama series that showcases the challenges and triumphs of emergency medical professionals.",
    actors: ["Igor Angelov", "Kamka Tocinovski"],
    directors: ["Goran Trenchovski"],
    awards: [],
    videoSrc: "http://example.com/brza_pomosh_trailer.mp4",
    writers: ["Nikola Kitanovski"],
    producers: ["MRT"],
    cinematography: ["Boris Mitkov"],
    costumeDesign: ["Marija Djeparoska"],
    editing: ["Aleksandar Belov"],
    views: 750,
  },
  {
    id: 4,
    title: "Bushava Azbuka",
    type: "Kids",
    genres: ["Family", "Educational"],
    posterImage: "/assets/images/bushava_azbuka.png",
    duration: 4554,
    releaseDate: "2000-05-01",
    storyline:
      "An educational series for children that teaches the Macedonian alphabet in a fun and engaging way.",
    description:
      "A beloved children's educational series that helps kids learn the Macedonian alphabet through songs and stories.",
    actors: ["Kiril Pop Hristov", "Marija Kondova"],
    directors: ["Aleksandar Popovski"],
    awards: [],
    videoSrc: "http://example.com/bushava_azbuka_trailer.mp4",
    writers: ["Biljana Crvenkovska"],
    producers: ["MRT"],
    cinematography: ["Goce Petrovski"],
    costumeDesign: ["Verica Atanasova"],
    editing: ["Aleksandar Belov"],
    views: 150,
  },
  {
    id: 5,
    title: "Dajte Muzika",
    type: "Kids",
    genres: ["Family", "Music"],
    posterImage: "/assets/images/dajte_muzika.png",
    duration: 125,
    releaseDate: "2008-02-15",
    storyline:
      "A musical series for children featuring songs and performances from popular Macedonian artists.",
    description:
      "An entertaining musical series that introduces children to the world of music and performance.",
    actors: ["Children of Macedonia"],
    directors: ["Ilija Cvetkovski"],
    awards: [],
    videoSrc: "http://example.com/dajte_muzika_trailer.mp4",
    writers: ["Ilija Cvetkovski"],
    producers: ["MRT"],
    cinematography: ["Boris Mitkov"],
    costumeDesign: ["Verica Atanasova"],
    editing: ["Ana Blazhevska"],
    views: 9250,
  },
  {
    id: 6,
    title: "Do Balcak",
    type: "Movie",
    genres: ["Drama", "Action"],
    posterImage: "/assets/images/Do_Balcak.png",
    duration: 150,
    releaseDate: "2014-09-18",
    storyline:
      "Set in 1900, a story about love, honor, and vengeance in the Balkan Peninsula.",
    description:
      "An epic historical drama showcasing the complex history and culture of Macedonia.",
    actors: ["Miki Manojlović", "Nikolina Kujaca"],
    directors: ["Stole Popov"],
    awards: [],
    videoSrc: "http://example.com/do_balcak_trailer.mp4",
    writers: ["Gordan Mihic"],
    producers: ["Geyzer Production"],
    cinematography: ["Dejan Dimeski"],
    costumeDesign: ["Marija Pirkovska"],
    editing: ["Atanas Georgiev"],
    views: 2890,
  },
  {
    id: 7,
    title: "Fifi and the Flowertots",
    type: "Kids",
    genres: ["Animation", "Children"],
    posterImage: "/assets/images/Fifi_and_the_Flowertots.png",
    duration: 251,
    releaseDate: "2005-05-02",
    storyline:
      "Follows the adventures of Fifi, a Flowertot, and her friends in the magical garden.",
    description:
      "An animated children's series filled with colorful characters and fun adventures.",
    actors: ["Jane Horrocks", "Maria Darling"],
    directors: ["Tim Harper"],
    awards: [],
    videoSrc: "http://example.com/fifi_and_the_flowertots_trailer.mp4",
    writers: ["Keith Chapman"],
    producers: ["Chapman Entertainment"],
    cinematography: ["John Lee"],
    costumeDesign: ["Sue Tong"],
    editing: ["Nigel Pickard"],
    views: 2890,
  },
  {
    id: 8,
    title: "Homo",
    type: "Documentary",
    genres: ["Biography", "History"],
    posterImage: "/assets/images/homo_poster.png",
    duration: 75,
    releaseDate: "2017-03-21",
    storyline:
      "A documentary exploring the life and work of a notable historical figure from Macedonia.",
    description:
      "An insightful documentary that delves into the personal and professional life of a Macedonian icon.",
    actors: [],
    directors: ["Ilija Cvetkovski"],
    awards: [],
    videoSrc: "http://example.com/homo_trailer.mp4",
    writers: ["Ilija Cvetkovski"],
    producers: ["MRT"],
    cinematography: ["Boris Mitkov"],
    costumeDesign: [""],
    editing: ["Ilija Cvetkovski"],
    views: 2890,
  },
  {
    id: 9,
    title: "Jaz Sem Frenk",
    type: "Movie",
    genres: ["Drama", "Comedy"],
    posterImage: "/assets/images/Jaz-Sem-Frenk.png",
    duration: 110,
    releaseDate: "2019-10-15",
    storyline:
      "Follows the story of Frenk, a man trying to navigate his life and relationships in contemporary Macedonia.",
    description:
      "A heartfelt comedy-drama that explores the ups and downs of life and love in modern Macedonia.",
    actors: ["Blagoj Veselinov", "Kamka Tocinovski"],
    directors: ["Gjorce Stavreski"],
    awards: [],
    videoSrc: "http://example.com/jaz_sem_frenk_trailer.mp4",
    writers: ["Gjorce Stavreski"],
    producers: ["Fragment Film"],
    cinematography: ["Dimo Popov"],
    costumeDesign: ["Viktorija Dejanova"],
    editing: ["Gjorce Stavreski"],
    views: 3890,
  },
  {
    id: 10,
    title: "Juzni vetar",
    type: "Series",
    genres: ["Action", "Crime", "Drama"],
    posterImage: "/assets/images/Juzni_vetar.png",
    duration: 120,
    releaseDate: "2018-11-12",
    storyline:
      "A young man from Serbia gets involved in the dangerous world of organized crime.",
    description:
      "An action-packed crime drama that dives into the gritty underworld of the Balkan region.",
    actors: ["Milos Bikovic", "Miodrag Radonjic"],
    directors: ["Milos Avramovic"],
    awards: ["Best TV Series at Serbian Academy Awards"],
    videoSrc: "http://example.com/juzni_vetar_trailer.mp4",
    writers: ["Petar Mihajlovic"],
    producers: ["Firefly Productions"],
    cinematography: ["Dejan Petrovic"],
    costumeDesign: ["Jelena Stokic"],
    editing: ["Aleksandar Popovic"],
    views: 2690,
  },
  {
    id: 11,
    title: "Kino Ljubov",
    type: "Documentary",
    genres: ["Documentary", "Biography"],
    posterImage: "/assets/images/kino-ljubov.png",
    duration: 80,
    releaseDate: "2012-06-10",
    storyline:
      "The life story of the first filmmaker in Macedonia, his achievements, and his contributions to the film industry.",
    description:
      "A touching documentary that highlights the pioneering work of Macedonia's first filmmaker and his lasting legacy.",
    actors: [],
    directors: ["Ilija Piperkoski"],
    awards: ["Macedonian Film Festival Award"],
    videoSrc: "http://example.com/kino_ljubov_trailer.mp4",
    writers: ["Ilija Piperkoski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Violeta Kalajdzieva"],
    views: 1890,
  },
  {
    id: 12,
    title: "Krvava svadba",
    type: "Movie",
    genres: ["Drama", "History"],
    posterImage: "/assets/images/Krvava_svadba.png",
    duration: 140,
    releaseDate: "2007-09-25",
    storyline:
      "Based on true events, this film portrays the tragic and tumultuous events during a wedding in a Macedonian village.",
    description:
      "A gripping historical drama that brings to life a true story of love, betrayal, and tragedy.",
    actors: ["Verica Nedeska", "Vlado Jovanovski"],
    directors: ["Stole Popov"],
    awards: ["Best Director Award at Skopje Film Festival"],
    videoSrc: "http://example.com/krvava_svadba_trailer.mp4",
    writers: ["Gordan Mihic"],
    producers: ["Geyzer Production"],
    cinematography: ["Dejan Dimeski"],
    costumeDesign: ["Marija Pirkovska"],
    editing: ["Atanas Georgiev"],
    views: 2390,
  },
  {
    id: 13,
    title: "Kuka na srekata",
    type: "Series",
    genres: ["Family", "Drama"],
    posterImage: "/assets/images/kuka_na_srekata.png",
    duration: 130,
    releaseDate: "2011-03-10",
    storyline:
      "A family drama that explores the lives and relationships of a large Macedonian family.",
    description:
      "A heartwarming series that captures the dynamics and emotions of family life in Macedonia.",
    actors: ["Nikola Ristanovski", "Vesna Petrushevska"],
    directors: ["Milcho Manchevski"],
    awards: ["Macedonian TV Award"],
    videoSrc: "http://example.com/kuka_na_srekata_trailer.mp4",
    writers: ["Milcho Manchevski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Violeta Kalajdzieva"],
    views: 1390,
  },
  {
    id: 14,
    title: "Lazar",
    type: "Movie",
    genres: ["Thriller", "Drama"],
    posterImage: "/assets/images/Lazar.png",
    duration: 100,
    releaseDate: "2015-12-15",
    storyline:
      "A suspenseful thriller about a man named Lazar who becomes entangled in a dangerous game of survival.",
    description:
      "An intense thriller that keeps the audience on the edge of their seats with its gripping storyline.",
    actors: ["Nikola Ristanovski", "Verica Nedeska"],
    directors: ["Svetozar Ristovski"],
    awards: [],
    videoSrc: "http://example.com/lazar_trailer.mp4",
    writers: ["Svetozar Ristovski"],
    producers: ["Geyzer Production"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Marija Pirkovska"],
    editing: ["Atanas Georgiev"],
    views: 4890,
  },
  {
    id: 15,
    title: "Liberation of Skopje",
    type: "Movie",
    genres: ["War", "Drama"],
    posterImage: "/assets/images/liberation_skopje.png",
    duration: 110,
    releaseDate: "2016-01-20",
    storyline:
      "Set during WWII, this film tells the story of a young boy witnessing the liberation of Skopje from Nazi occupation.",
    description:
      "A poignant war drama that explores the impact of WWII on a young boy and his family in Skopje.",
    actors: ["David Todosovski", "Rade Serbedzija"],
    directors: ["Rade Serbedzija"],
    awards: ["Best Foreign Language Film"],
    videoSrc: "http://example.com/liberation_of_skopje_trailer.mp4",
    writers: ["Dušan Jovanović"],
    producers: ["MRT"],
    cinematography: ["Dejan Dimeski"],
    costumeDesign: ["Viktorija Dejanova"],
    editing: ["Atanas Georgiev"],
    views: 3890,
  },
  {
    id: 16,
    title: "Makedonska saga",
    type: "Movie",
    genres: ["Drama", "History"],
    posterImage: "/assets/images/makedonska-saga-poster.png",
    duration: 120,
    releaseDate: "1993-11-15",
    storyline:
      "A dramatic tale spanning decades, following the lives of a Macedonian family through significant historical events.",
    description:
      "An epic drama that captures the essence of Macedonian history and culture through the lens of one family.",
    actors: ["Boris Dvornik", "Radmila Zivkovic"],
    directors: ["Branko Gapo"],
    awards: ["Golden Arena Award"],
    videoSrc: "http://example.com/makedonska_saga_trailer.mp4",
    writers: ["Gordan Mihic"],
    producers: ["Vardar Film"],
    cinematography: ["Goce Gavrilovski"],
    costumeDesign: ["Marija Pirkovska"],
    editing: ["Aleksandar Belov"],
    views: 3542,
  },
  {
    id: 17,
    title: "Na granici",
    type: "Series",
    genres: ["Drama", "Crime"],
    posterImage: "/assets/images/na_granici.png",
    duration: 100,
    releaseDate: "2018-10-22",
    storyline:
      "A crime drama series set in a border town, exploring the lives of those involved in smuggling and law enforcement.",
    description:
      "A gritty crime drama that delves into the complex and often dangerous world of border town life.",
    actors: ["Toni Mihajlovski", "Emil Ruben"],
    directors: ["Aleksandar Popovski"],
    awards: [],
    videoSrc: "http://example.com/na_granici_trailer.mp4",
    writers: ["Biljana Crvenkovska"],
    producers: ["MRT"],
    cinematography: ["Dejan Dimeski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Aleksandar Belov"],
    views: 2690,
  },
  {
    id: 18,
    title: "Mirage",
    type: "Movie",
    genres: ["Drama", "Thriller"],
    posterImage: "/assets/images/Mirage.png",
    duration: 90,
    releaseDate: "2004-03-15",
    storyline:
      "A young boy dreams of escaping his harsh reality in a Macedonian town, but life takes an unexpected turn.",
    description:
      "A haunting and powerful drama that captures the struggle and dreams of a young boy in Macedonia.",
    actors: ["Marko Kovacevic", "Aljoša Vuckovic"],
    directors: ["Svetozar Ristovski"],
    awards: ["Special Jury Award at Sundance"],
    videoSrc: "http://example.com/mirage_trailer.mp4",
    writers: ["Svetozar Ristovski"],
    producers: ["Vardar Film"],
    cinematography: ["Dejan Dimeski"],
    costumeDesign: ["Viktorija Dejanova"],
    editing: ["Atanas Georgiev"],
    views: 2860,
  },
  {
    id: 19,
    title: "Nashe malo",
    type: "Kids",
    genres: ["Family", "Comedy"],
    posterImage: "/assets/images/nashe_malo.png",
    duration: 90,
    releaseDate: "2002-04-10",
    storyline:
      "A light-hearted comedy series about the everyday lives of a small community in Macedonia.",
    description:
      "A charming and humorous series that highlights the quirks and joys of small-town life in Macedonia.",
    actors: ["Vesna Petrushevska", "Vlado Jovanovski"],
    directors: ["Mile Stojanov"],
    awards: [],
    videoSrc: "http://example.com/nashe_malo_trailer.mp4",
    writers: ["Mile Stojanov"],
    producers: ["MRT"],
    cinematography: ["Goce Petrovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Ana Blazhevska"],
    views: 3690,
  },
  {
    id: 20,
    title: "Petko",
    type: "Kids",
    genres: ["Family", "Children"],
    posterImage: "/assets/images/Petko.png",
    duration: 80,
    releaseDate: "2010-09-05",
    storyline:
      "A children's series about a playful dog named Petko and his adventures with his young owner.",
    description:
      "An entertaining and educational series for children, focusing on the fun and lessons learned from Petko's adventures.",
    actors: ["Petko the Dog", "Simona Stojanovska"],
    directors: ["Mile Stojanov"],
    awards: ["Best Children's Program"],
    videoSrc: "http://example.com/petko_trailer.mp4",
    writers: ["Mile Stojanov"],
    producers: ["MRT"],
    cinematography: ["Goce Petrovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Ana Blazhevska"],
    views: 6390,
  },
  {
    id: 21,
    title: "Power Puf Gurls",
    type: "Kids",
    genres: ["Action", "Comedy"],
    posterImage: "/assets/images/PowerPufGurls.png",
    duration: 90,
    releaseDate: "2001-12-15",
    storyline:
      "Three super-powered girls fight villains and save their city from various threats.",
    description:
      "An action-packed and humorous animated series about three young girls with extraordinary powers.",
    actors: ["Tara Strong", "Cathy Cavadini"],
    directors: ["Craig McCracken"],
    awards: ["Annie Award for Best Animated Television Production"],
    videoSrc: "http://example.com/power_puf_gurls_trailer.mp4",
    writers: ["Craig McCracken"],
    producers: ["Cartoon Network Studios"],
    cinematography: ["Ernie Hudson"],
    costumeDesign: ["Karyn Wagner"],
    editing: ["Jon Foster"],
    views: 890,
  },
  {
    id: 22,
    title: "Samuraj Jack",
    type: "Kids",
    genres: ["Action", "Adventure"],
    posterImage: "/assets/images/SamurajJack.png",
    duration: 95,
    releaseDate: "2001-08-10",
    storyline:
      "A samurai from ancient Japan is sent to a dystopian future and must find a way back to his own time.",
    description:
      "An epic animated series that blends action, adventure, and stunning visuals as Samurai Jack battles to return to the past.",
    actors: ["Phil LaMarr", "Mako Iwamatsu"],
    directors: ["Genndy Tartakovsky"],
    awards: ["Primetime Emmy Award"],
    videoSrc: "http://example.com/samuraj_jack_trailer.mp4",
    writers: ["Genndy Tartakovsky"],
    producers: ["Cartoon Network Studios"],
    cinematography: ["Scott Wills"],
    costumeDesign: ["Genndy Tartakovsky"],
    editing: ["Brian A. Miller"],
    views: 690,
  },
  {
    id: 23,
    title: "Senki",
    type: "Movie",
    genres: ["Drama", "Mystery"],
    posterImage: "/assets/images/Senki-2007.png",
    duration: 120,
    releaseDate: "2007-10-10",
    storyline:
      "A man begins to experience strange occurrences after surviving a car accident, uncovering secrets from his past.",
    description:
      "A suspenseful drama that delves into the mysterious and supernatural events surrounding a man's life after a near-fatal accident.",
    actors: ["Borce Nacev", "Vesna Petrushevska"],
    directors: ["Milcho Manchevski"],
    awards: ["Best Macedonian Film"],
    videoSrc: "http://example.com/senki_trailer.mp4",
    writers: ["Milcho Manchevski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Violeta Kalajdzieva"],
    views: 9890,
  },
  {
    id: 24,
    title: "Sestri",
    type: "Movie",
    genres: ["Drama", "Family"],
    posterImage: "/assets/images/sestri.png",
    duration: 100,
    releaseDate: "2015-05-20",
    storyline:
      "A heartwarming tale of two sisters navigating life's challenges and supporting each other through thick and thin.",
    description:
      "A poignant family drama that highlights the unbreakable bond between two sisters and their journey through life's ups and downs.",
    actors: ["Verica Nedeska", "Nikola Ristanovski"],
    directors: ["Milcho Manchevski"],
    awards: [],
    videoSrc: "http://example.com/sestri_trailer.mp4",
    writers: ["Milcho Manchevski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Violeta Kalajdzieva"],
    views: 9890,
  },
  {
    id: 25,
    title: "Tetoviranje",
    type: "Movie",
    genres: ["Drama", "Crime"],
    posterImage: "/assets/images/tetoviranje-poster.png",
    duration: 110,
    releaseDate: "1991-09-15",
    storyline:
      "A gritty crime drama about a man who gets caught up in the underworld of illegal tattooing and organized crime.",
    description:
      "A dark and intense drama that explores the dangerous world of illegal tattooing and the criminal underworld.",
    actors: ["Borce Nacev", "Vesna Petrushevska"],
    directors: ["Stole Popov"],
    awards: ["Golden Leopard Award"],
    videoSrc: "http://example.com/tetoviranje_trailer.mp4",
    writers: ["Gordan Mihic"],
    producers: ["Vardar Film"],
    cinematography: ["Dejan Dimeski"],
    costumeDesign: ["Marija Pirkovska"],
    editing: ["Aleksandar Belov"],
    views: 9990,
  },
  {
    id: 26,
    title: "The man in the movie camera",
    type: "Documentary",
    genres: ["Documentary", "Biography"],
    posterImage: "/assets/images/the-man-in-the-movie-camera.png",
    duration: 85,
    releaseDate: "2017-04-12",
    storyline:
      "The life and works of a pioneering cinematographer who transformed the film industry with his innovative techniques.",
    description:
      "An inspiring documentary that celebrates the groundbreaking achievements of a visionary cinematographer.",
    actors: [],
    directors: ["Ilija Piperkoski"],
    awards: ["Macedonian Film Festival Award"],
    videoSrc: "http://example.com/the_man_in_the_movie_camera_trailer.mp4",
    writers: ["Ilija Piperkoski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Violeta Kalajdzieva"],
    views: 290,
  },
  {
    id: 27,
    title: "Treto poluvreme",
    type: "Movie",
    genres: ["Sports", "Drama"],
    posterImage: "/assets/images/treto-poluvreme.png",
    duration: 130,
    releaseDate: "2012-09-15",
    storyline:
      "A historical sports drama about a football team in Macedonia during WWII and their struggle against Nazi oppression.",
    description:
      "An inspiring and emotional sports drama that highlights the power of unity and resilience in the face of adversity.",
    actors: ["Sasko Kocev", "Katarina Ivanovska"],
    directors: ["Darko Mitrevski"],
    awards: ["Audience Award at Skopje Film Festival"],
    videoSrc: "http://example.com/treto_poluvreme_trailer.mp4",
    writers: ["Darko Mitrevski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Marija Pirkovska"],
    editing: ["Aleksandar Belov"],
    views: 6690,
  },
  {
    id: 28,
    title: "Vrba",
    type: "Movie",
    genres: ["Drama", "History"],
    posterImage: "/assets/images/Vrba.png",
    duration: 115,
    releaseDate: "2019-11-20",
    storyline:
      "A historical drama that intertwines three stories of love, faith, and sacrifice spanning different centuries in Macedonia.",
    description:
      "A beautifully crafted historical drama that weaves together three tales of love and devotion across time.",
    actors: ["Sara Klimoska", "Nikola Ristanovski"],
    directors: ["Milcho Manchevski"],
    awards: ["Best Macedonian Film"],
    videoSrc: "http://example.com/vrba_trailer.mp4",
    writers: ["Milcho Manchevski"],
    producers: ["MRT"],
    cinematography: ["Vladimir Samoilovski"],
    costumeDesign: ["Elena Ivanova"],
    editing: ["Violeta Kalajdzieva"],
    views: 4890,
  },
  {
    id: 29,
    title: "Zlatno slavejce",
    type: "Kids",
    genres: ["Family", "Animation"],
    posterImage: "/assets/images/zlatno_slavejce.png",
    duration: 90,
    releaseDate: "2007-12-20",
    storyline:
      "A heartwarming animated film about a golden nightingale and its magical song.",
    description:
      "Zlatno Slavejce is a Macedonian animated film that tells the story of a golden nightingale with a magical song that brings happiness to everyone who hears it.",
    actors: ["N/A"],
    directors: ["Trajce Gjorgiev"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["Trajce Gjorgiev"],
    producers: ["Pero Stojanovski"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 2890,
  },
  {
    id: 30,
    title: "Zona zamfirova",
    type: "Movie",
    genres: ["Drama", "Romance"],
    posterImage: "/assets/images/Zona_zamfirova.png",
    duration: 120,
    releaseDate: "2002-10-16",
    storyline:
      "A romantic drama set in 19th-century Belgrade, revolving around the love between a beautiful young girl, Zona, and a young Italian nobleman, Andrea.",
    description:
      "Zona Zamfirova is a Serbian romantic drama film directed by Zdravko Šotra, based on the 1879 novel of the same name by Stevan Sremac.",
    actors: ["Katarina Radivojevic", "Vojin Cetkovic"],
    directors: ["Zdravko Šotra"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["Stevan Sremac (novel)", "Gordan Mihic (screenplay)"],
    producers: ["N/A"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 2290,
  },
  {
    id: 31,
    title: "Ice Age",
    type: "Movie",
    genres: ["Animation", "Adventure", "Comedy"],
    posterImage: "/assets/images/ice-age.jpg",
    duration: 81,
    releaseDate: "2002-03-15",
    storyline:
      "A group of prehistoric animals embark on a journey to return a human baby to its tribe.",
    description:
      "Ice Age is a 2002 animated film directed by Chris Wedge and Carlos Saldanha. It follows a woolly mammoth, a sloth, and a sabre-toothed tiger who join forces to return a human baby to its tribe.",
    actors: ["Ray Romano", "John Leguizamo", "Denis Leary"],
    directors: ["Chris Wedge", "Carlos Saldanha"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["Michael J. Wilson", "Michael Berg"],
    producers: ["Lori Forte"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 6890,
  },
  {
    id: 32,
    title: "Familija markovski",
    type: "Series",
    genres: ["Comedy", "Family"],
    posterImage: "/assets/images/familija-markovski.jpg",
    storyline:
      "A comedic portrayal of a typical Macedonian family, dealing with everyday life in a humorous way.",
    description:
      "Familija Markovski is a popular Macedonian TV show that humorously depicts the life of a typical Macedonian family.",
    actors: ["Nikola Ristanovski", "Labina Mitevska", "Petar Mircevski"],
    directors: ["N/A"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["N/A"],
    producers: ["N/A"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 7890,
  },
  {
    id: 33,
    title: "Monsters",
    type: "Movie",
    genres: ["Adventure", "Comedy", "Family"],
    posterImage: "/assets/images/monsters.jpg",
    duration: 92,
    releaseDate: "2001-11-02",
    storyline:
      "Two monsters, Sulley and Mike, work at a scream processing factory and find themselves caring for a human child, Boo, whom they accidentally bring into the monster world.",
    description:
      "Monsters, Inc. is a 2001 animated film directed by Pete Docter. It follows the story of two monsters, Sulley and Mike, who work at a scream processing factory and discover the importance of laughter.",
    actors: ["John Goodman", "Billy Crystal", "Mary Gibbs"],
    directors: ["Pete Docter", "David Silverman", "Lee Unkrich"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["Pete Docter", "Jill Culton", "Jeff Pidgeon", "Ralph Eggleston"],
    producers: ["Darla K. Anderson"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 3390,
  },
  {
    id: 34,
    title: "Narcos",
    type: "Series",
    genres: ["Biography", "Crime", "Drama"],
    posterImage: "/assets/images/narcos.jpg",
    storyline:
      "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.",
    description:
      "Narcos is a Netflix original series that chronicles the rise of the cocaine trade in Colombia and the gripping real-life stories of drug kingpins of the late '80s.",
    actors: ["Wagner Moura", "Boyd Holbrook", "Pedro Pascal"],
    directors: ["N/A"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["Carlo Bernard", "Chris Brancato", "Doug Miro"],
    producers: ["N/A"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 4490,
  },
  {
    id: 35,
    title: "Power",
    type: "Series",
    genres: ["Crime", "Drama"],
    posterImage: "/assets/images/power.jpg",
    storyline:
      "A successful nightclub owner tries to navigate the treacherous world of New York City nightlife while also dealing with his complex love life.",
    description:
      "Power is a crime drama TV series that follows James St. Patrick, a wealthy nightclub owner who leads a double life as a drug kingpin. As he tries to leave the criminal world behind, he faces numerous challenges and betrayals.",
    actors: ["Omari Hardwick", "Lela Loren", "Naturi Naughton"],
    directors: ["N/A"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["Courtney A. Kemp"],
    producers: ["N/A"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 2290,
  },
  {
    id: 36,
    title: "Toy Story",
    type: "Kids",
    genres: ["Animation", "Adventure", "Comedy"],
    posterImage: "/assets/images/toy-story.jpg",
    duration: 81,
    releaseDate: "1995-11-22",
    storyline:
      "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    description:
      "Toy Story is a 1995 American computer-animated comedy film produced by Pixar Animation Studios and released by Walt Disney Pictures. It is the first installment in the Toy Story franchise.",
    actors: ["Tom Hanks", "Tim Allen", "Don Rickles"],
    directors: ["John Lasseter"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: [
      "John Lasseter",
      "Pete Docter",
      "Andrew Stanton",
      "Joe Ranft",
      "Joss Whedon",
      "Joel Cohen",
      "Alec Sokolow",
    ],
    producers: ["Bonnie Arnold", "Ralph Guggenheim"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 3890,
  },
  {
    id: 37,
    title: "Zoki Poki",
    type: "Kids",
    genres: ["Comedy", "Family"],
    posterImage: "/assets/images/zoki-poki.jpg",
    storyline:
      "A heartwarming comedy about a mischievous boy named Zoki who brings joy and laughter to his family and friends.",
    description:
      "Zoki Poki is a Macedonian comedy film that follows the adventures of a young boy named Zoki as he navigates through life with his playful antics and infectious laughter.",
    actors: ["Blagoj Veselinov", "Zoran Radanov", "Petar Temelkovski"],
    directors: ["N/A"],
    videoSrc: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    writers: ["N/A"],
    producers: ["N/A"],
    cinematography: ["N/A"],
    costumeDesign: ["N/A"],
    editing: ["N/A"],
    views: 2890,
  },
];
